version: "3.9"

services:
  app:
    build: .
    container_name: service-now
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - postgres
    

  postgres:
    image: postgres:16
    container_name: service-now-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=servicenow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: