name: service-now

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Local .env
        run: |
          cp /home/shubhamrwt/service-now/backend/.env .env

      - name: Show Docker Version
        run: docker --version

      - name: Stop Containers
        run: docker compose -f docker-compose.yml down || true

      - name: Build and Start
        run: docker compose -f docker-compose.yml up -d --build

      - name: Show Running Containers
        run: docker ps